### PR TITLE
Add support for glob imports

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Port of https://github.com/meteor/meteor/pull/9272 to add support for `@import` of globs, e.g. `@import './folder/*'`. All credit goes to @mitar.

I need this because I’m using [Vuetify](https://vuetifyjs.com) in my app, and it has Stylus files that I want to pull in via:

```styl
@import '{}/node_modules/vuetify/src/stylus/main'
```

Without this PR, the above line fails because of the glob that Vuetify uses in its `main.styl` file:

```
failed to locate @require file ./settings/*.styl
```

With this PR, it works.

Branched off of https://github.com/coagmano/meteor-stylus/pull/5, [here is the diff from that PR](https://github.com/GeoffreyBooth/meteor-stylus/compare/fix-tests…GeoffreyBooth:glob).

image

### CODE REVIEW

**Comment by mitar** [comment]
Yes, this was exactly the reason why I wanted to use importing, to import Veutify which is also what I am using. But at the end I just gave up on that because it seems Stylus as a whole is not really supported much, so I ended up importing built CSS directly. So now [I am just using imports in CSS](https://github.com/peer/doc/blob/devel/client/lib/index.css) and [postcss import resolver](https://github.com/peer/doc/blob/devel/.postcssrc.js#L4).

**Comment by GeoffreyBooth** [comment]
@coagmano Any concerns with this?

**Comment by coagmano** [comment]
Sorry I missed this PR, I must have lost the notification!

No concerns, will merge and publish now

**Comment by GeoffreyBooth** [comment]
Thanks, do you mind please publishing to Atmosphere?

**Comment by coagmano** [comment]
Just stress testing it on a few projects, one is refusing to build so might take a bit

**Comment by coagmano** [comment]
Yeah something is wrong, it's taking forever to build and when I debug it, it's spending a lot of time searching for plugins.

I added some logs here:
```
function resolvePath(path) {
  let paths = glob.sync(path);
  if (paths.length === 0) {
    console.log('test glob here', path)
    paths = glob.sync(`**/${path}`);
    console.log('test glob 2', paths)
  }
  return paths;
}
```
Which gives this:
```
test glob here client/modules/m_modelViewer/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/stylus/lib/functions.styl
test glob here client/modules/m_modelViewer/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/nib.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/nib/normalize.styl
test glob here client/modules/m_modelViewer/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/normalize.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/nib/text.styl
test glob here client/modules/m_modelViewer/text.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/text.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/text.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/text.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/text.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/text.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/text.styl
test glob here client/modules/m_modelViewer/axis.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/axis.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/axis.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/axis.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/axis.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/axis.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/axis.styl
test glob here client/modules/m_modelViewer/rupture.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/rupture.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/rupture.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/rupture.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/rupture.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/rupture.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/rupture.styl
test glob here client/modules/m_modelViewer/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/typographic/stylus/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/rupture/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/axis/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl
test glob here /Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/nib/lib/Users/fredstark/displayground/packages/stylus/.npm/plugin/compileStylusBatch/node_modules/jeet/styl.styl

```
Each run through ``paths = glob.sync(`**/${path}`);`` takes ~2s before `test glob 2` logs.

Which looks like for it's trying to find the included plugin files in every plugin's folder every time for every file. ( On³ maybe? )

I'm testing it in a project with 74 styl files, it looks like it does 51 searches for each file, so that means compiling will take an extra ~7,548s (~2hrs) 😰 

Removing the ``paths = glob.sync(`**/${path}`);`` line speeds it up, but it's still a bit slow, so I'll see if I can get it to ignore plugin paths

**Comment by coagmano** [comment]
I'm, still struggling to get this to work properly.

In my case, I have several packages which add a lot of stylus files directly instead of an entry-point followed by imports. 
It seems that because this compiler creates a new instance of the stylus renderer for each file added directly, it also has to start each file by importing the stylus plugins. 
Each plugin adds it's own directory to `paths`.
The plugin files all end up going through `resolvePath` joined to each of the paths.

The solution is probably identifying which of the imports are builtins or plugins [like we do here](https://github.com/coagmano/meteor-stylus/blob/master/plugin/compile-stylus.js#L154-L173), and skipping the glob search.

I had a go at doing that [in a new branch here](https://github.com/coagmano/meteor-stylus/blob/fix-slow-glob/plugin/compile-stylus.js#L129-L136), but it still isn't helping.

I'm thinking it would help for this and generally to create the stylus renderer instance once and re-use it for each file. But I am unsure how much state is kept between calls to `render` and if that would cause even more problems

**Comment by GeoffreyBooth** [comment]
Can you post a repo that’s a simple example of a project that demonstrates the issue you’re seeing?

**Comment by coagmano** [comment]
Here you go:

https://github.com/coagmano/meteor-stylus-glob-repro

Here's the steps I followed to set it up
1. meteor create meteor-stylus-glob
1. download and extract latest master of `coagmano:stylus` into `packages`
1. meteor add`coagmano:stylus`
1. rename `client/main.css` to `client/main.styl`
1. instrument `resolvePath` `compile-stylus.js` with logs:
```
function resolvePath(path) {
  let paths = glob.sync(path);
  if (paths.length === 0) {
    console.log(`stylus glob could not find paths in ${paths}, trying **/${path}`)
    console.time('stylus glob.sync')
    paths = glob.sync(`**/${path}`);
    console.timeEnd('stylus glob.sync')
    console.log(`stylus glob finished searching **/${path}`)
  }
  return paths;
}
```

You can see that builds take longer than normal, and that the section in question is called a few too many times

**Comment by GeoffreyBooth** [comment]
I might have time this weekend to look into this, unless @mitar do you have any time? It's your code 😉

**Comment by GeoffreyBooth** [comment]
@coagmano I think the issues you’re seeing are what @hwillson was talking about in https://github.com/meteor/meteor/pull/9272#issuecomment-348249629. I think we need to revert his two commits (https://github.com/meteor/meteor/pull/9272/commits/bd45da4ca56bb29ca418c38ad643de95d8c267ba, https://github.com/meteor/meteor/pull/9272/commits/5e30fad64b66c46c6bd9a25443131c07cc76d46c) where he hacked a solution for the “Meteor Tool in dev mode with local packages” case, and find a better solution for that case (and add tests for it). cc @mitar

Alternatively, local packages wanting to use Stylus could keep using `mdg:stylus`, and this package simply drops support for that case. My impression is that the “organize your app into lots of local packages” style is a lot less popular now than it was a few years ago, now that we have explicit load order via `imports` or the `package.json` `"meteor"` entry point field. How important is Stylus support in local packages?

**Comment by coagmano** [comment]
Thanks for this. I'm back at work on Monday and will run it against our project then.

We use local packages extensively, and I feel like a compiler plugin should support that use case.
Are you talking about package imports, or any `.styl` file in a local package? 

I think we can get away with not supporting package imports, as long as files added with `api.addFiles` or imported from a `.js` file work (We have a lot of shared blaze components that use either method for adding stylus files).

Maybe globing can be disabled with a feature flag for the odd case like mine?

Either way, this is looking like a major version bump, even just the switch to explicit import style for the plugins is a breaking change (which I'm okay with).

**Comment by GeoffreyBooth** [comment]
> Are you talking about package imports, or any `.styl` file in a local package?

I wrote more about this in #7. I don’t have good examples of Stylus files used in packages (local or not) and I can’t figure out how we would write tests for that that work in `meteor test-packages`, so I don’t really know how to handle that case. I got your example repo working with #7, but I’m worried that it’s so minimal that it doesn’t cover all the cases of Stylus files in local packages. I guess if #7 doesn’t work well with one of your real projects, maybe you can update the example repo with a bit more detail to make it more fleshed out?

A few general thoughts:

- Yes, this should be a major version bump.

- Any Stylus plugins that don’t require the `.use` call should perhaps be removed, because couldn’t they be `@import`-ed? Especially now that we have support for globs. Whatever plugins we can remove should speed up compilation performance.

- Perhaps we should remove the half-finished “variables from JSON files” code?

- Is there some way to take a string like `{namespace:package-name}` and resolve the file path to that package? Or even a reasonable list of places it could be, like I need to check `<app root>/.meteor/local/packages/namespace/package-name` and `<app root>/packages/namespace/package-name` or something like that, but no paths beyond those two or few. Then we would never need the problematic `**/`.

**Pull request merged**
